services:
- docker

language: python
python:
  - "3.6"

install:
  - pip install pipenv pew
  - pipenv install -e .
  - pipenv install --dev

script:
  - coverage run --source dockerpath -m py.test

after_script:
  - pip install --quiet coveralls && coveralls
